version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./keycloak/dump/db-backup-23-11-22.sql:/docker-entrypoint-initdb.d/db-backup-23-11-22.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always
  keycloak:
    build:
      dockerfile: keycloak/docker/DockerFile
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8081:8081
      - 8443:8443
    depends_on:
      - postgres
    command:
      - start-dev
      - --http-port=8081
    entrypoint:
      - /opt/keycloak/bin/kc.sh