server:
  error:
    ## white-label error-page 비활성화
    whitelabel:
      enabled: false
    ## 오류 응답에 stacktrace 내용을 포함할지 여부
    include-stacktrace: never
  port: 8090

keycloak:
  realm: development
  grant_type: client_credentials
  auth-server-url: http://localhost:8080
  clientId: internal-services
  client_secret: ASLelSDoDqTuPEODKUpantzkivy7xiRc

logging:
  level:
    root: debug

spring:
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:8080/realms/development/protocol/openid-connect/token/introspect
          client-id: internal-services
          client-secret: ASLelSDoDqTuPEODKUpantzkivy7xiRc